### ISSUE TITLE
.zshenv cannot load nvm

### ISSUE THREAD

**Issue by saintwinkle** [SublimeLinter/SublimeLinter-coffeelint#19]
I am using `zsh` & `nvm`, so I've followed the 3rd step in "Linter installation", but `.zshenv` cannot load `nvm`.
Relogin or restart the system cannot help either.

What exactly should I do?

**Comment by Blumed** [comment]
https://github.com/creationix/nvm#manual-install

I have to use this snippet `. ~/.nvm/nvm.sh` to initialize my shell. I can then use `nvm use 0.10.3` in order to boss nvm around.

Does this help?

**Comment by saintwinkle** [comment]
@Blumed 

Yes, that's helped! Thanks!

I think the reason is that I've used `install.sh` to load `nvm`, so I move the default script from `zshrc` to `.zshenv`:
``` bash
export NVM_DIR="$NVM_DIR"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
But it doesn't work. (I'm not familiar with bash script so don't know why :-|) Then I use `. ~/.nvm/nvm.sh` instead, everything just goes well.

Thank you very much! :smile:

**Comment by Blumed** [comment]
Glad I could help :)
