### ISSUE TITLE
Linter doesn't use nearest coffeelint.json file

### ISSUE THREAD

**Issue by morleyzhi** [SublimeLinter/SublimeLinter-coffeelint#20]
In summary, the linter uses the top-most `coffeelint.json` file it finds, instead of the nearest. That means that we can't use directory-level overrides.

Here's a repo that reproduces this case:

https://github.com/morleyzhi/sublime-coffeelint-cascade

If you clone and open `forty-chars/test.coffee` and save, you would expect it to use `forty-chars/coffeelint.json`, but it doesn't, according to the Sublime console (and the lint results):

```
SublimeLinter: coffeelint: test.coffee ['C:\\Users\\Morley\\AppData\\Roaming\\npm\\coffeelint.cmd', '--reporter', 'jslint', '--stdin', '-f', 'C:\\Users\\Morley\\Documents\\GitHub\\sublime-coffeelint-cascade\\forty-chars\\coffeelint.json']

**Comment by feugy** [comment]
Seems to work in v1.1.6, because SublimeLinter does the "bubble search" [by itself](http://www.sublimelinter.com/en/latest/linter_attributes.html?highlight=config_file#config-file).

@morleyzhi, Is the problem still here ?

**Comment by morleyzhi** [comment]
Looks like it's fixed now, thanks!
