### ISSUE TITLE
Allow to set configuration file in plugin settings

### ISSUE THREAD

**Issue by feugy** [SublimeLinter/SublimeLinter-coffeelint#23]
I'd like to change the configuration filename from `coffeelint.json` to `.coffeelintrc`

It's possible to override the entire "-f" option in plugin settings:

```
{
  "user": {
    "linters": {
      "coffeelint": {
        "@disable": false,
        "args": ["-f", "${project}/.coffeelintrc"],
        "excludes": []
      }
    }
  }
}
```

But in this case, we can't use the "bubble search" of the file [performed by SublimeLinter](http://www.sublimelinter.com/en/latest/linter_attributes.html?highlight=config_file#config-file)

A better solution could be to let user specify the file name in settings, and use it in the `config_file` linter attribute, instead of [having it hard-coded](https://github.com/SublimeLinter/SublimeLinter-coffeelint/blob/master/linter.py#L34)

Does it seem doable ?

**Comment by Onumis** [comment]
Bump. Need this.

**Comment by thgreasi** [comment]
Need this too 👍

**Comment by thgreasi** [comment]
actually this worked for me as of 2017-06-23. Should this be closed?

**Comment by braver** [comment]
The proposed solution, passing it as an argument, is the correct one. The special handling of config_file is slated for removal in SublimeLinter 4.
