### ISSUE TITLE
coffeelint.json exact file path in Sublime 3

### ISSUE THREAD

**Issue by RaghavendhraK** [SublimeLinter/SublimeLinter-coffeelint#26]
Hi,
It might be very basic question, but I need the answer. Where should I put the coffeelint.json file, so that SublimeLinter picks these settings.
Thanks,
Raghu

**Comment by jakkor** [comment]
It should be in the main folder of your project.

**Comment by braver** [comment]
SublimeLinter doesn't read the config file, coffeelint does. SublimeLinter "merely" runs coffeelint, and coffeelint will look for the config file.
