### ISSUE TITLE
coffeelint.json configuration files in SublimeLinter 4 

### ISSUE THREAD

**Issue by fmasuhr** [SublimeLinter/SublimeLinter-coffeelint#29]
As of version 4 of SublimeLinter the support for the `config_file` is removed (https://github.com/SublimeLinter/SublimeLinter/issues/891). Therefore it is no longer possible to use the project specific `coffeelint.json` configuration files. 

In the old implementation SL was checking the tree upwards till the file was found. But now each linter should handle this on their own.
Coffeelint does support this behavior as well but not for `stdin` executions.

Therefore the old behavior needs to be implemented for SL-coffeelint again (maybe similar to https://github.com/oschwald/SublimeLinter-perlcritic/pull/7)

**Comment by kaste** [comment]
Ah, well. Honestly, I think perlcritic's approach a bit over-engineered. 

AFAIK coffelint configuration can also be in packages.json which was never supported by SL3. Now the simple solution is probably to just add

```
defaults = {
	'-f': '${folder:~}/coffeelint.json'
}
```

(I think that's the correct Sublime DSL usage here, but I always have to look it up.)

You can try this right now. Every linter has the `args` setting. 

```
	"args": ["-f", "${folder:~}/coffeelint.json"]
```

should 🤞 just work. 

(If perlcritic just added that, and if it works LOL, 90% use case ✔️ )

**Comment by fmasuhr** [comment]
@kaste Thank you for the fast response on this. 

But I tested this and if I am not mistaken this is only working when the `coffeelint.json` file is located on the root of the project folder. But this does not rebuild something similar to the old behavior. E.g when the `coffeelint.json` is not located on root it does not work. 

The behavior of checking the tree upwards till there is a config files is something which was working with SL 3 and is also working in coffeelint when listing files and not `stdin`. In my case I got the following structure of folders which I open in Sublime text:

```
projects/
├── project1/
│   ├── coffeelint.json
│   └── ...
├── project2/
│   ├── coffeelint.json
│   └── ...
└── project3/
    └── ...
```

When using this it does not work with the suggested solution

**Comment by fmasuhr** [comment]
You are right this would actually work. But this way I need to add each project manually and this is a bit inconvenient.

Actually the old implementation in SL was dropped because linters implement the very useful feature of automatic config detection by themselves in the meantime. But the specific usage of `stdin` within this SL plugin id breaking this for coffeelint. So I think it is worth implementing the old behavior to get this also working for coffeelint as other SL plugins also supporting this.

**Comment by kaste** [comment]
I also looked at this linter at that time. The problem here was that we never looked into packages.json and it was not configurable by the user. 

Why not solve it over at the linter? If it is well organized it should somewhere have a function 'get_config_file(file_dir)'.

**Comment by kaste** [comment]
It is https://github.com/clutchski/coffeelint/blob/master/src/configfinder.coffee

Actually first looks for an ENV var, then for packages.json, then coffeelint.json, finally in the home dir.

**Comment by kaste** [comment]
I just read through it, this would be a super simple PR. Of course we need a flag to pass in a filename like -stdin-filename

**Comment by kaste** [comment]
I was about to PR this. But, look here

https://github.com/clutchski/coffeelint/blob/99f56ed7e5b0a813d148fb595d84031af39d21f4/src/configfinder.coffee#L16-L17

It seems that it looks for `cwd`. So probably if you set `"working_dir": "${file}"` in your linter settings, it should just work. 🎉

**Comment by fmasuhr** [comment]
Thank you for checking the source. In the meantime I actually found out that I was wrong about the missing support for the automatic detection of config when using `stdin`. This is wrongly documented in coffeelint.

I also know know how to get it working with the auto detection.
I need to configure the `working_dir`
```
"working_dir": "${file_path}"
```

**Comment by kaste** [comment]
Haha, we found it at the exact same time.

**Comment by fmasuhr** [comment]
Haha :D Thanks a lot again. So this is fixed then for me ;)

**Comment by kaste** [comment]
So if we do a PR here, we should just set the working_dir to $file instead of $folder.

**Comment by fmasuhr** [comment]
Yes that should be probably the default for this linter to work properly out of the box

**Comment by kaste** [comment]
So I made a PR https://github.com/SublimeLinter/SublimeLinter-coffeelint/pull/30 Can you check this, and if I didn't make it stupid I could release it.

**Comment by fmasuhr** [comment]
@kaste It is working now, Thanks a lot

**Comment by geoffreak** [comment]
What version was this fix released as? I'm on version 2.1.1 and I can't get it to read my coffeelint.json files ever since SL 4. I have a folder open in Sublime Text with the coffeelint.json file in the root of the folder and regardless of what file I have open, my rules won't apply. I can tell that the plugin is working because it shows errors with syntax errors, but it isn't following any of my rules specified in the file.

I tried adding the args as described above, but it doesn't seem to make any difference in any file I have open either.
```js
// SublimeLinter Settings - User
{
  "linters": {
    "coffeelint": {
      "args": ["-f", "${folder:~}/coffeelint.json"]
    }
  },
}
```

**Comment by geoffreak** [comment]
Okay, this gets weirder. I see SL picking up the coffeelint.json file correctly and I can see it detecting the problems using my coffeelint.json... but nothing shows up outside the gutter or status bar.

```
SublimeLinter: #989 SublimeLinter.sublime-package:746: 'coffee' is linting 'catch.coffee'
SublimeLinter: #990 SublimeLinter.sublime-package:746: 'coffeelint' is linting 'catch.coffee'
SublimeLinter: #989 SublimeLinter.sublime-package:1044: coffee: catch.coffee ['/usr/local/bin/coffee', '--compile', '--stdio']
SublimeLinter: #989 SublimeLinter.sublime-package:1047: coffee: cwd: /Users/me/code/project
SublimeLinter: #990 SublimeLinter.sublime-package:1044: coffeelint: catch.coffee ['/Users/me/code/project/node_modules/.bin/coffeelint', '--reporter', 'jslint', '--stdin']
SublimeLinter: #990 SublimeLinter.sublime-package:1047: coffeelint: cwd: /Users/me/code/project/folder
SublimeLinter: #990 SublimeLinter.sublime-package:773: coffeelint output:
    <?xml version="1.0" encoding="utf-8"?><jslint>
    <file name="stdin">
    <issue line="15"
            lineEnd="15"
            reason="[warn] Undefined identifier &quot;badVariableNam&quot;"
            evidence="undefined"/>
    </file>
    </jslint>
```

If I make a change that also gets detected by the other linter, `SublimeLinter-coffee`, it shows up in the gutter and status bar. The logs are different from coffeelint and don't show XML.

```
SublimeLinter: #991 SublimeLinter.sublime-package:773: coffee output:
    [stdin]:15:12: error: unexpected ..
      badVariab..leNam
               ^^
SublimeLinter: #991 SublimeLinter.sublime-package:814: coffee: No match for line: '  badVariab..leNam'
SublimeLinter: #991 SublimeLinter.sublime-package:814: coffee: No match for line: '           ^^'
SublimeLinter: #992 SublimeLinter.sublime-package:773: coffeelint output:
    <?xml version="1.0" encoding="utf-8"?><jslint>
    <file name="stdin">
    <issue line="15"
            lineEnd="15"
            reason="[error] [stdin]:15:12: error: unexpected ..
      badVariab..leNam
               ^^"
            evidence="undefined"/>
    </file>
    </jslint>
```

So I guess this might be a different issue? Still not sure what exactly is going on here.

**Comment by kaste** [comment]
> but nothing shows up outside the gutter or status bar

What does that even mean? You can also open `SublimeLinter: Show all errors` which opens a panel. If you just don't see the underlines/highlighted regions that's clearly unrelated and maybe you have to fix your applied styles.

**Comment by geoffreak** [comment]
Thanks for your help so far. I don't think this is a styling problem.

The status bar I'm referring to is the bar at the bottom of SublimeText. Yes, I don't see any underlines/highlights inside the editor from SL-coffeelint, but I do for SL-coffee and SL-eslint. This is something that broke for me after SL4 came out without any other changes.

As you can see in the following images, SL-coffeelint renders nothing, but SL-coffee and SL-eslint render as expected. SL-coffeelint used to render like the other two.

![imv5p1tp3l9pbormf87fje4mp1zhvfj0bwc](https://user-images.githubusercontent.com/338037/38095887-230b70ee-3337-11e8-80a0-440ca710e212.png)

![lc4t1vu961cjqjsh5gyx8vssc56qtjie5xw](https://user-images.githubusercontent.com/338037/38095952-49256ef6-3337-11e8-8e1a-d4f41cc2c12e.png)

![xis7x984vwuu2zal0omhvtoa6huyobhsm6n](https://user-images.githubusercontent.com/338037/38096250-0a2b38b0-3338-11e8-8816-1cdc685f0966.png)

**Comment by fmasuhr** [comment]
@geoffreak I can confirm that this is also missing for me

**Comment by kaste** [comment]
Okay thank you for the pictures. That's indeed a bug with outline style I fixed this week or so. In it is the new release from today.

**Comment by kaste** [comment]
Lol. *braver released it today.

**Comment by geoffreak** [comment]
Just checked again with SL 4.2.1 and we have visible errors again! The status bar is now correctly showing the error message, but...

There's still a bit of an issue with the display though. It only highlights the first character in the line regardless of where in the line the issue is. This issue is only present in SL-coffeelint of course. No visible changes to SL-coffee.

![4llsu49kss86ox2de8u2cvu5lq4zw73ubh1](https://user-images.githubusercontent.com/338037/38098909-d51248c4-333e-11e8-9f50-743983423d55.png)

![1bnqxk8llhc6rwxmhrgcx9qqcnllc9zanrr](https://user-images.githubusercontent.com/338037/38099019-24c170f2-333f-11e8-98a7-66a58bcf1b75.png)

If there's a better issue somewhere else to follow up with this, let me know.

**Comment by fmasuhr** [comment]
@geoffreak I just checked coffeelint and it seems like there was no support for columns. I do not remember how it looked like before the SL 4 Upgrade but when checking the regex for SL-coffeelint it seems like the `col` attribute never worked.
So the suggested switch to another reported or changes to the regex will not fix this as long as coffeelint does not support it.

There is now a PR (https://github.com/clutchski/coffeelint/pull/632) in coffeelint to add general support for columns but it seems like the repository is kind of unmaintained.

**Comment by geoffreak** [comment]
That makes sense. I think what I'm remembering is that SL3 would just mark the entire row with an icon in the gutter. Whenever the row was clicked into (at any column) the status bar would update to show the error or warning text. Now, only the first character of the line is highlighted and will show the updated status bar text. This makes it much more difficult to get the error information as only when the cursor is on the first column or two does the error message display.

This would look not unlike the picture posted above (and shown below), except the warning would show up in ST's bottom bar (status bar) after the line/column numbers.

![](https://user-images.githubusercontent.com/338037/38095887-230b70ee-3337-11e8-80a0-440ca710e212.png)

**Comment by kaste** [comment]
There is a setting

```
    // Determines what happens when a linter reports a problem without column.
    // By default, a mark is put in the gutter and the first character is highlighted.
    // If this setting is `true`, the entire line is also highlighted.
    "no_column_highlights_line": false,
```

Still we would need a different reporter to get rid of the html encoded entities. 

As @geoffreak posted we have no column e.g. here 

```
    <?xml version="1.0" encoding="utf-8"?><jslint>
    <file name="stdin">
    <issue line="15"
            lineEnd="15"
            reason="[warn] Undefined identifier &quot;badVariableNam&quot;"
            evidence="undefined"/>
    </file>
    </jslint>
```

and usual col info here 

```
    <?xml version="1.0" encoding="utf-8"?><jslint>
    <file name="stdin">
    <issue line="15"
            lineEnd="15"
            reason="[error] [stdin]:15:12: error: unexpected ..
      badVariab..leNam
               ^^"
            evidence="undefined"/>
    </file>
    </jslint>
```

The latter has all we need in the `reason`, but the warn above has not even a line in the reason. Hope you guys find a sane reporter setting here. Post the raw output and we sure can write a regex.

**Comment by aminland** [comment]
I went through all these motions which is why eventually i gave up on straight coffeelint and just started using Sublime-eslint.
I published a version of coffeelint with coffee2 support and columns in output (npm [@fellow/coffeelint2](https://npmjs.com/package/@fellow/coffeelint2), but you shouldnt need to use it directly, and instead can just use my eslint coffee plugin at [@fellow/eslint-plugin-coffee](https://npmjs.com/package/@fellow/eslint-plugin-coffee)

Just make sure to change the "selector" settings for eslint in the sublimelinter settings:
`"selector": "source.cjsx, source.coffee, source.js"`

**Comment by kaste** [comment]
Eventually eslint will also handle php and python files. 😁
